### ISSUE TITLE
Crash on 3.14

### ISSUE THREAD

**Issue by Willoxey** [thebigsmileXD/Backpack#12]
Description

Crash on teleporting to another world wearing a backpack.

Here's the crashdump
[Tue_Jun_30-03.51.14-UTC_2020.log](https://github.com/thebigsmileXD/Backpack/files/4854003/Tue_Jun_30-03.51.14-UTC_2020.log)

**Comment by Willoxey** [comment]
Will it be updated :?? Please?

**Comment by inxomnyaa** [comment]
🤔💭

**Comment by Willoxey** [comment]
:( it's not working D:
now i have a tinysmileXD cuz i cant use backpacks on my server.

My cute baby fix it. I've fixed it but the virions that i were using they were outdated ;(
