### ISSUE TITLE
Plugin doesn't work - "GD library is not enabled"

### ISSUE THREAD

**Issue by ndggaming** [thebigsmileXD/Backpack#2]
Hi, I have tested your project in my server but it doesn't work. In the console of my server it's written :

`"2019-10-23 [16:43:59] [Server thread/CRITICAL]: pocketmine\plugin\PluginException: "GD library is not enabled! Please uncomment gd2 in php.ini!" (EXCEPTION) in "plugins/Backpack_dev-1 (1).phar/src/xenialdan/Backpack/Loader" at line 71"`
(I think it's the same problem as Benda in his MyEntities plugin)

I know that the plugin is new but I send you that if it can help you ^^

**Comment by ndggaming** [comment]
Ho sorry I did not read the informations ...

**Comment by inxomnyaa** [comment]
> Ho sorry I did not read the informations ...

-.-
Fuck it. Why did i even spent 2 hours on creating the README. I quit, fuck coding.
